name: LiteProfiles
version: '@version@'
main: me.darwj.liteprofiles.LiteProfiles
api-version: '1.20'
depend: [PlaceholderAPI]
commands:
  liteprofiles:
    description: Admin command of LiteProfiles.
    permission: liteprofiles.command.liteprofiles
  profile:
    description: Manage your profiles.
    aliases:
      - account
      - pf
    permission: liteprofiles.command.profile
